services:
  - type: web
    name: rt-cod-boost
    env: node
    plan: free
    buildCommand: |
      echo "=== Installation dépendances racine ==="
      npm install
      echo "=== Installation dépendances WEB (là où est l'app) ==="
      cd web && npm install
      echo "=== Vérification installation ==="
      cd web && ls node_modules | head -10
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "18.20.4"
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false