# render.yaml - Configuration pour le déploiement Render
services:
  - type: web
    name: rt-cod-boost
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: "write_orders,read_products,write_customers"
      - key: HOST
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cod-boost-db
          property: connectionString

databases:
  - name: cod-boost-db
    databaseName: cod_boost_production
    plan: free