services:
  - type: web
    name: rt-cod-boost
    env: node
    plan: free
    buildCommand: |
      echo "Installing root dependencies..."
      npm install --omit=dev
      echo "Installing web dependencies..."
      cd web && npm install --omit=dev
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "18.20.4"
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false