# render.yaml - Configuration pour le déploiement Render
services:
  - type: web
    name: rt-cod-boost
    env: node
    plan: free
    buildCommand: |
      echo "=== Installation dépendances racine ==="
      npm install
      echo "=== Installation dépendances web ==="
      cd web && npm install --production=false
      echo "=== Vérification des modules installés ==="
      cd web && ls -la node_modules/@shopify/ || echo "Modules Shopify non trouvés"
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "18.20.4"
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false