name = "RT COD BOOST"
client_id = "2bdd3ddbfa8761a72630a5989fe9cb29"
application_url = "https://cod-rt-boost.onrender.com"
embedded = true

[auth]
redirect_urls = [
  "https://cod-rt-boost.onrender.com/auth/callback",
  "https://cod-rt-boost.onrender.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rt-solutions-test.myshopify.com"

[access_scopes]
scopes = "read_orders,write_orders,read_products,write_products"

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
